---
title: jastiso.github.io
timezone: EST
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Jennifer Stiso
markdown: kramdown
permalink: /news/:year/:month/:day/:title
